/* tslint:disable */
/* eslint-disable */
/**
 * Online Go Server REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ChallengesGameTimeControlParameters,
    ChallengesGameTimeControlParametersFromJSON,
    ChallengesGameTimeControlParametersFromJSONTyped,
    ChallengesGameTimeControlParametersToJSON,
} from './';

/**
 * 
 * @export
 * @interface ChallengesGame
 */
export interface ChallengesGame {
    /**
     * 
     * @type {string}
     * @memberof ChallengesGame
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ChallengesGame
     */
    rules: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChallengesGame
     */
    ranked: boolean;
    /**
     * 
     * @type {number}
     * @memberof ChallengesGame
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof ChallengesGame
     */
    height: number;
    /**
     * 
     * @type {number}
     * @memberof ChallengesGame
     */
    handicap: number;
    /**
     * 
     * @type {string}
     * @memberof ChallengesGame
     */
    komiAuto: string;
    /**
     * 
     * @type {number}
     * @memberof ChallengesGame
     */
    komi: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChallengesGame
     */
    disableAnalysis: boolean;
    /**
     * 
     * @type {number}
     * @memberof ChallengesGame
     */
    initialState: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChallengesGame
     */
    _private: boolean;
    /**
     * 
     * @type {string}
     * @memberof ChallengesGame
     */
    timeControl: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChallengesGame
     */
    pauseOnWeekends: boolean;
    /**
     * 
     * @type {ChallengesGameTimeControlParameters}
     * @memberof ChallengesGame
     */
    timeControlParameters: ChallengesGameTimeControlParameters;
}

export function ChallengesGameFromJSON(json: any): ChallengesGame {
    return ChallengesGameFromJSONTyped(json, false);
}

export function ChallengesGameFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengesGame {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'rules': json['rules'],
        'ranked': json['ranked'],
        'width': json['width'],
        'height': json['height'],
        'handicap': json['handicap'],
        'komiAuto': json['komi_auto'],
        'komi': json['komi'],
        'disableAnalysis': json['disable_analysis'],
        'initialState': json['initial_state'],
        '_private': json['private'],
        'timeControl': json['time_control'],
        'pauseOnWeekends': json['pause_on_weekends'],
        'timeControlParameters': ChallengesGameTimeControlParametersFromJSON(json['time_control_parameters']),
    };
}

export function ChallengesGameToJSON(value?: ChallengesGame | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'rules': value.rules,
        'ranked': value.ranked,
        'width': value.width,
        'height': value.height,
        'handicap': value.handicap,
        'komi_auto': value.komiAuto,
        'komi': value.komi,
        'disable_analysis': value.disableAnalysis,
        'initial_state': value.initialState,
        'private': value._private,
        'time_control': value.timeControl,
        'pause_on_weekends': value.pauseOnWeekends,
        'time_control_parameters': ChallengesGameTimeControlParametersToJSON(value.timeControlParameters),
    };
}

