/* tslint:disable */
/* eslint-disable */
/**
 * Online Go Server REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ChallengesGame,
    ChallengesGameFromJSON,
    ChallengesGameFromJSONTyped,
    ChallengesGameToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    initialized: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    minRanking: number;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    maxRanking: number;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    challengerColor: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    agaRanked: boolean;
    /**
     * 
     * @type {ChallengesGame}
     * @memberof InlineObject
     */
    game: ChallengesGame;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return InlineObjectFromJSONTyped(json, false);
}

export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'initialized': json['initialized'],
        'minRanking': json['min_ranking'],
        'maxRanking': json['max_ranking'],
        'challengerColor': json['challenger_color'],
        'agaRanked': json['aga_ranked'],
        'game': ChallengesGameFromJSON(json['game']),
    };
}

export function InlineObjectToJSON(value?: InlineObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'initialized': value.initialized,
        'min_ranking': value.minRanking,
        'max_ranking': value.maxRanking,
        'challenger_color': value.challengerColor,
        'aga_ranked': value.agaRanked,
        'game': ChallengesGameToJSON(value.game),
    };
}

